name: workflow.yml
on: push

jobs:
  compile:
    name: Compile assets
    runs-on: ubuntu-latest
    steps:
      - name : Check out the repo
        uses: actions/checkout@v3
      - name : Run Docker container to compile assets
        uses : docker://
